# crm_models.py — Generated by Solo IA Brain
from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime, UTC
import enum

Base = declarative_base()

class LeadStatus(str, enum.Enum):
    NEW = "new"
    CONTACTED = "contacted"
    QUALIFIED = "qualified"
    PROPOSAL = "proposal"
    NEGOTIATION = "negotiation"
    WON = "won"
    LOST = "lost"

class Lead(Base):
    __tablename__ = "crm_leads"
    id = Column(Integer, primary_key=True)
    company = Column(String(255), nullable=False)
    contact_name = Column(String(255))
    email = Column(String(255))
    phone = Column(String(50))
    status = Column(Enum(LeadStatus), default=LeadStatus.NEW)
    score = Column(Float, default=0.0)
    source = Column(String(100))
    estimated_value = Column(Float, default=0.0)
    probability = Column(Float, default=0.0)
    notes = Column(Text)
    assigned_to = Column(String(255))
    tags = Column(String(500))
    created_at = Column(DateTime, default=lambda: datetime.now(UTC))
    updated_at = Column(DateTime, default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))
    deals = relationship("Deal", back_populates="lead")
    activities = relationship("Activity", back_populates="lead")
    
    def to_dict(self):
        result = {}
        for c in self.__table__.columns:
            val = getattr(self, c.name)
            if isinstance(val, datetime):
                val = val.isoformat()
            result[c.name] = val
        return result

class Deal(Base):
    __tablename__ = "crm_deals"
    id = Column(Integer, primary_key=True)
    lead_id = Column(Integer, ForeignKey("crm_leads.id"))
    name = Column(String(255), nullable=False)
    stage = Column(String(50), default="discovery")
    amount = Column(Float, default=0.0)
    currency = Column(String(3), default="USD")
    closing_date = Column(DateTime)
    probability = Column(Float, default=0.0)
    notes = Column(Text)
    created_at = Column(DateTime, default=lambda: datetime.now(UTC))
    updated_at = Column(DateTime, default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))
    lead = relationship("Lead", back_populates="deals")
    activities = relationship("Activity", back_populates="deal")

class Activity(Base):
    __tablename__ = "crm_activities"
    id = Column(Integer, primary_key=True)
    lead_id = Column(Integer, ForeignKey("crm_leads.id"))
    deal_id = Column(Integer, ForeignKey("crm_deals.id"), nullable=True)
    type = Column(String(50))
    subject = Column(String(255))
    description = Column(Text)
    due_date = Column(DateTime, nullable=True)
    completed = Column(Boolean, default=False)
    created_by = Column(String(255))
    created_at = Column(DateTime, default=lambda: datetime.now(UTC))
    lead = relationship("Lead", back_populates="activities")
    deal = relationship("Deal", back_populates="activities")
