# supabase_config.py — Generated by Solo Engine v2
# Supabase provides Postgres + Auth + Storage (like blink.new)
import os

# Set these env vars (from your Supabase project dashboard)
SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://YOUR-PROJECT.supabase.co")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "YOUR-SUPABASE-ANON-KEY")  # anon/public key

# Schema for CRM (matches crm_models.py)
LEADS_TABLE = "crm_leads"
DEALS_TABLE = "crm_deals"

# For Auth (JWT)
SUPABASE_JWT_SECRET = os.environ.get("SUPABASE_JWT_SECRET", "")


def get_supabase_client():
    """Return a Supabase client if a real URL is configured, else None."""
    if "YOUR-PROJECT" in SUPABASE_URL:
        return None
    try:
        from supabase import create_client
        return create_client(SUPABASE_URL, SUPABASE_KEY)
    except Exception:
        return None
